// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhwFscRMyg5WLsCaoYJ2JCU49TzEuSryc',
    appId: '1:818967875128:web:85655d46322f6e9ad960cd',
    messagingSenderId: '818967875128',
    projectId: 'example-shop-sudocodellc',
    authDomain: 'example-shop-sudocodellc.firebaseapp.com',
    storageBucket: 'example-shop-sudocodellc.appspot.com',
    measurementId: 'G-6B3WJER912',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnQlErG6IJsP94yZV7x_JWbZakzRVEAng',
    appId: '1:818967875128:android:af610130eaf9b4d7d960cd',
    messagingSenderId: '818967875128',
    projectId: 'example-shop-sudocodellc',
    storageBucket: 'example-shop-sudocodellc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL0AgLXM3lTieHQMYGSt0bOmvZoPuu-Gg',
    appId: '1:818967875128:ios:45f9ba81f5289025d960cd',
    messagingSenderId: '818967875128',
    projectId: 'example-shop-sudocodellc',
    storageBucket: 'example-shop-sudocodellc.appspot.com',
    iosBundleId: 'com.sudocodellc.exampleShopSudocodellc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL0AgLXM3lTieHQMYGSt0bOmvZoPuu-Gg',
    appId: '1:818967875128:ios:fbd686027150855fd960cd',
    messagingSenderId: '818967875128',
    projectId: 'example-shop-sudocodellc',
    storageBucket: 'example-shop-sudocodellc.appspot.com',
    iosBundleId: 'com.sudocodellc.exampleShopSudocodellc.RunnerTests',
  );
}
